import type { Artifact, User, Proposal } from './types';
import { PlaceHolderImages } from './placeholder-images';

function getPlaceholder(id: string) {
  return PlaceHolderImages.find(p => p.id === id) || PlaceHolderImages[0];
}

export const artifacts: Artifact[] = [
  {
    id: '1',
    name: 'I Can Has Cheezburger?',
    era: '2007 Meme Era',
    description: 'A quintessential "lolcat" macro featuring a British Shorthair cat, it became one of the most famous internet memes of the late 2000s.',
    category: 'Meme',
    archiveHash: '0x' + Buffer.from('I Can Has Cheezburger?0xAb...C101672614400').toString('hex'),
    uploader: '0xAb...C10',
    timestamp: 1672614400,
    imageUrl: getPlaceholder('artifact-1').imageUrl,
    imageHint: getPlaceholder('artifact-1').imageHint,
  },
  {
    id: '2',
    name: 'Windows 95 UI',
    era: 'Web1',
    description: 'The user interface of Windows 95, which introduced the Start menu and taskbar, defining the desktop paradigm for decades.',
    category: 'UI',
    archiveHash: '0x' + Buffer.from('Windows 95 UI0xCd...E341147587200').toString('hex'),
    uploader: '0xCd...E34',
    timestamp: 1147587200,
    imageUrl: getPlaceholder('artifact-2').imageUrl,
    imageHint: getPlaceholder('artifact-2').imageHint,
  },
  {
    id: '3',
    name: 'GeoCities Homepage',
    era: 'Age of Flash',
    description: 'A classic GeoCities homepage, characterized by animated GIFs, visitor counters, and vibrant, often clashing, colors.',
    category: 'Website',
    archiveHash: '0x' + Buffer.from('GeoCities Homepage0xFe...A58933888000').toString('hex'),
    uploader: '0xFe...A58',
    timestamp: 933888000,
    imageUrl: getPlaceholder('artifact-3').imageUrl,
    imageHint: getPlaceholder('artifact-3').imageHint,
  },
  {
    id: '4',
    name: 'Space Invader Pixel Art',
    era: 'Early Gaming',
    description: 'Pixel art of an alien from the 1978 arcade game Space Invaders, an icon of 8-bit gaming culture.',
    category: 'Other',
    archiveHash: '0x' + Buffer.from('Space Invader Pixel Art0xAb...C101420156000').toString('hex'),
    uploader: '0xAb...C10',
    timestamp: 1420156000,
    imageUrl: getPlaceholder('artifact-4').imageUrl,
    imageHint: getPlaceholder('artifact-4').imageHint,
  },
  {
    id: '5',
    name: 'AIM Chat Snippet',
    era: 'Early 2000s',
    description: 'A conversation from AOL Instant Messenger (AIM), showing the slang and emoticons of the era.',
    category: 'Text',
    archiveHash: '0x' + Buffer.from('AIM Chat Snippet0x12...F671041404000').toString('hex'),
    uploader: '0x12...F67',
    timestamp: 1041404000,
    imageUrl: getPlaceholder('artifact-5').imageUrl,
    imageHint: getPlaceholder('artifact-5').imageHint,
  },
  {
    id: '6',
    name: 'The Dancing Baby',
    era: 'The First Viral Video',
    description: 'A 3D rendered animation of a baby dancing, it was one of the first pieces of content to go viral on the internet in the late 90s.',
    category: 'Meme',
    archiveHash: '0x' + Buffer.from('The Dancing Baby0xCd...E34852073600').toString('hex'),
    uploader: '0xCd...E34',
    timestamp: 852073600,
    imageUrl: getPlaceholder('artifact-6').imageUrl,
    imageHint: getPlaceholder('artifact-6').imageHint,
  },
  {
    id: '7',
    name: 'Badger Badger Badger',
    era: 'Age of Flash',
    description: 'A looping Flash animation featuring badgers, a mushroom, and a snake. A hallmark of early 2000s internet randomness.',
    category: 'Website',
    archiveHash: '0x' + Buffer.from('Badger Badger Badger0xFe...A581057039200').toString('hex'),
    uploader: '0xFe...A58',
    timestamp: 1057039200,
    imageUrl: getPlaceholder('artifact-7').imageUrl,
    imageHint: getPlaceholder('artifact-7').imageHint,
  },
  {
    id: '8',
    name: 'Winamp Skin',
    era: 'Digital Music Dawn',
    description: 'A custom skin for the Winamp media player. Skinning was a popular way to personalize desktop applications.',
    category: 'UI',
    archiveHash: '0x' + Buffer.from('Winamp Skin0x12...F67978300800').toString('hex'),
    uploader: '0x12...F67',
    timestamp: 978300800,
    imageUrl: getPlaceholder('artifact-8').imageUrl,
    imageHint: getPlaceholder('artifact-8').imageHint,
  },
  {
    id: '9',
    name: 'Early Twitter "Twt"',
    era: 'Early Social Media',
    description: 'The design of a tweet from the early days of Twitter, showcasing the platform\'s original, simpler aesthetic.',
    category: 'UI',
    archiveHash: '0x' + Buffer.from('Early Twitter "Twt"0xAb...C101173906400').toString('hex'),
    uploader: '0xAb...C10',
    timestamp: 1173906400,
    imageUrl: getPlaceholder('artifact-9').imageUrl,
    imageHint: getPlaceholder('artifact-9').imageHint,
  },
  {
    id: '10',
    name: 'All Your Base',
    era: 'Early 2000s',
    description: 'A famous mistranslated phrase from the 1992 video game Zero Wing that became a massive internet meme.',
    category: 'Meme',
    archiveHash: '0x' + Buffer.from('All Your Base0xCd...E34981152000').toString('hex'),
    uploader: '0xCd...E34',
    timestamp: 981152000,
    imageUrl: getPlaceholder('artifact-10').imageUrl,
    imageHint: getPlaceholder('artifact-10').imageHint,
  },
  {
    id: '11',
    name: 'Flash Game UI',
    era: 'Age of Flash',
    description: 'User interface elements from a typical Flash game, reminiscent of an era of browser-based gaming on sites like Newgrounds.',
    category: 'UI',
    archiveHash: '0x' + Buffer.from('Flash Game UI0xFe...A581136156000').toString('hex'),
    uploader: '0xFe...A58',
    timestamp: 1136156000,
    imageUrl: getPlaceholder('artifact-11').imageUrl,
    imageHint: getPlaceholder('artifact-11').imageHint,
  },
  {
    id: '12',
    name: 'Nyan Cat',
    era: '2011 Meme Era',
    description: 'An 8-bit animation of a cat with a Pop-Tart body flying through space, leaving a rainbow trail. A symbol of early 2010s internet optimism.',
    category: 'Meme',
    archiveHash: '0x' + Buffer.from('Nyan Cat0x12...F671302000000').toString('hex'),
    uploader: '0x12...F67',
    timestamp: 1302000000,
    imageUrl: getPlaceholder('artifact-12').imageUrl,
    imageHint: getPlaceholder('artifact-12').imageHint,
  }
];

export const proposals: Proposal[] = [
  {
    id: 'p1',
    title: 'Select the Artifact of the Week',
    description: 'Vote for which artifact should be crowned "Artifact of the Week" and featured on the homepage.',
    status: 'active',
    options: [
      { id: '1', label: 'I Can Has Cheezburger?', votes: 128 },
      { id: '2', label: 'Windows 95 UI', votes: 95 },
      { id: '6', label: 'The Dancing Baby', votes: 210 },
      { id: '12', label: 'Nyan Cat', votes: 180 },
    ],
    totalVotes: 613,
  },
  {
    id: 'p2',
    title: 'Next Featured Era: Web1 or Age of Flash?',
    description: 'Choose which historical era the Main Hall should focus on for the next exhibit cycle.',
    status: 'active',
    options: [
      { id: 'era-web1', label: 'Web1 (1991-2004)', votes: 450 },
      { id: 'era-flash', label: 'Age of Flash (1999-2010)', votes: 388 },
    ],
    totalVotes: 838,
  },
  {
    id: 'p3',
    title: 'Add "All Your Base" to the Main Hall?',
    description: 'Should the "All Your Base Are Belong to Us" artifact be granted a permanent spot in the Main Hall collection?',
    status: 'closed',
    options: [
      { id: 'yes', label: 'Yes, add it', votes: 987 },
      { id: 'no', label: 'No, keep it in the gallery', votes: 102 },
    ],
    totalVotes: 1089,
  },
];

export const user: User = {
  walletAddress: '0x12...F67',
  archeologistRank: 'Senior Curator',
  participationScore: 85,
  contributions: ['5', '8', '11', '12'],
  votesCast: [
    { proposalId: 'p2', optionId: 'era-flash' },
    { proposalId: 'p3', optionId: 'yes' },
  ],
};
